### ISSUE TITLE
Requires user to refer to the operations repo

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/services#17]
The user is required to refer to the operations repo for the beacon names. Only select beacons from the operations repo should be exposed to the user, which would also act as a list of available beacons.

Somewhat related, these beacon names don't match the beacons from the docs https://docs.api3.org/beacon/v0.1/reference/beacon-ids.html (`ETH/USD` vs. `eth_usd`)

**Comment by wkande** [comment]
This is where the docs **[read](https://github.com/api3dao/operations/blob/main/data/documentation_metadata.json)** the Beacon info.

**Comment by bbenligiray** [comment]
@aquarat Can you update how https://github.com/api3dao/services/issues/17#issuecomment-1036080491 is generated so that there is a `beaconName` in https://github.com/api3dao/operations/blob/main/data/documentation_metadata.json that uses the beacon file names? This is needed for the user to be able to use https://github.com/api3dao/services/blob/b5c1cda8eff44f729b90173ea98ab38eb3b10dc2/src/index.ts#L27 by referring to the docs.

**Comment by aquarat** [comment]
I will investigate, thanks :)

**Comment by aquarat** [comment]
The `documentation_metadata.json` is generated by the `export-docs` command in operations. It runs as a pre-commit hook currently. The idea is that the documentation metadata is always programmatically generated from the contents of the repository.

The `rename-beacons` command in the same repository allows a user to add both names and descriptions to beacons and templates (they're currently duplicated). The names and descriptions are stored as fields in the beacon files but they are also made file-system safe and used as the beacon and template file names.

To update the documentation names we just have to modify the [`export-documentation` script](https://github.com/api3dao/operations/blob/main/src/export-documentation.ts).

I will create a PR with the changes such that `documentation_metadata.json` will contain `beaconName`s with the filenames of the beacons.

**Comment by aquarat** [comment]
Looking at https://github.com/api3dao/services/blob/b5c1cda8eff44f729b90173ea98ab38eb3b10dc2/src/index.ts#L27
the filename is sanitised through a function in the operations repository (`sanitiseFilename`), so it could be added to the beacon path and then using the docs template name would resolve to the correct file. Example:
```
const goBeaconData = goSync(() => require(`@api3dao/operations/data/apis/${apiName}/beacons/${beaconName}`));
```
to
```
import { sanitiseFilename } from '@api3dao/operations/src/utils';

const goBeaconData = goSync(() => require(`@api3dao/operations/data/apis/${apiName}/beacons/${sanitiseFilename(beaconName)}.json`));
```
Is this acceptable?

**Comment by bbenligiray** [comment]
@aquarat That sounds like the best solution in the short term. We can discuss alternative solutions later on (the current convention doesn't work when we'll have an equivalent Beacon like ETH/USD powered by two different API providers).
